---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Education

**Columbia University Mailman School of Public Health**, New York, NY       
**Master of Science**, Environmental Health Data Science    

**Iona University**, New Rochelle, NY     
**Bachelor of Science**, Economics    
**Bachelor of Arts**, Political Science/Public Policy Track   
**Bachelor of Arts**, International Studies       


# Professional Experience

**Columbia University**, New York, NY    
_Research Assistant_ | May 2025 - Present  

Community Health Advisory & Information Network (CHAIN) Project 

*   Assist in the collection, cleaning, and analysis of quantitative and qualitative data    

*   Support the development of research proposals, including drafting sections and organizing supporting materials   

**Rutgers University**, New Brunswick, NJ    
_Sports Data Analyst_ | August 2024 - Present  

*   Design and conduct statistical analysis of team performance data using tools like R and Python, generating actionable insights for diverse audiences

*   Collaborate with stakeholders to identify trends in data, informing strategy and aligning with team goals    

**Pinnacle Volleyball Academy**, West Nyack, NY    
_Assistant Coach/Technical Director_ | December 2019 - Present  

*   Partner with coaching staff to design practice plans and game strategies informed by player performance metrics and opponent analytics for 100+ athletes

*   Conduct in-depth video breakdowns and statistical analysis to evaluate player efficiency, success rates, and game impact to enhance player IQ and decision-making    

**Iona University**, New Rochelle, NY    
_NCAA Division I Student-Athlete_ | August 2020 - May 2024  

*   Conducted scouting reports on opposing teams by analyzing video footage, identifying offensive/defensive tendencies, and contributing to match strategies

*   Collaborated with teammates and staff to implement tactical adjustments based on data-driven insights, including serve/receive patterns, hitting efficiency and blocking schemes    

*   Developed leadership, communication, and analytical skills in a high-pressure, team-oriented environment       

# Research Experience

**Associations between PFAS exposure with early reproductive health in females and males and fertility outcomes: A cross-sectional ecological study at the county level**   
Advisor: Jeremy Porter, PhD and Matt Perzanowski, PhD, MPH

**Assessing Aedes aegypti activity and dengue infection using CMIP5 temperature projections for Los Angeles, California: an exercise in temperature-dependent variability**   
Advisor: Wan Yang, PhD

**Drinking Water Contamination and Low Birth Weight in California: A Statistical Analysis**    
Advisor: Marianthi-Anna Kioumourtzoglou, ScD, MSPH

**Elk Expeditions: The Elk, the Environment, and the Evolving Migration in Yellowstone**   
Advisor: Jeff Goldsmith, PhD 

**Ecotourism and the Exploitation of Small Island Developing States**                                   
_A Case Study of Rural Communities in the Dominican Republic_   
Advisor: Jeanne Zaino, PhD  

*   Built econometric models using national and regional data to assess sustainability outcomes in rural communities

*   Applied software tools such as Gretl to evaluate economic trends and proposed evidence-based recommendations for policy improvements

**Conspicuous Consumption and the Role of the Fast Fashion Industry in Consumer Behavior**      	
_A Case Study of H&M, Zara, and Shein_    
Advisor: Robert Lacey, PhD

*   Conducted statistical analyses to evaluate market strategies and consumer behavior trends in the fast fashion industry

*   Analyzed cost-effectiveness and ethical business practices, providing insights on consumer purchasing decisions       


# Skills and Certifications

**Data Analysis and Statistics**: R/R Studio, Python, SQL, SPSS, Gretl, Tableau, Power BI   
**Language Skills**: English, Spanish   
**Certifications**: Biomedical Research (CITI), Social/Behavioral Research (CITI), Human Subjects Protection Biomed (CITI)       

# Related Coursework

*   Data Science I/II   
*   Biostatistical Methods I/II   
*   Advanced GIS and Spatial Analysis   
*   Advanced Analytical Methods in Environmental Health Sciences    
*   Epi Modeling for Infectious Diseases    
*   Environmental Determinants of Human Health II

