---
title: "NY NOAA"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r}
library(flexdashboard)
library(tidyverse)
library(plotly)
```

```{r}
ny_noaa = read_csv(file = "./data/nynoaadat.csv") |> 
  janitor::clean_names() |> 
  mutate(
    year = year(date), 
    month = month(date),
    day = day(date)
  )
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

Total Precipitation vs. Total Snow Depth in December 2009
```{r}
ny_noaa |> 
  filter(year == 2009 & month == 12) |>
  
  plot_ly(
    x = ~day) |> 
  add_bars(y = ~prcp, name = "Total Precipitation", marker = list(color = '#21918c')) |> 
  add_bars(y = ~snwd, name = "Total Snow Depth", marker = list(color = '#440154'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

Total Precipitation from 2000-2010
```{r}
ny_noaa |> 
  filter(year == c(2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010)) |> 
  mutate(
    text_label = 
      str_c("ID: ", id, 
            "Precipitation: ", prcp, 
            "Date: ", date)) |> 
  plot_ly(
    x = ~year, y = ~prcp, color = ~year, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5)
```

### Chart C

Average Precipitation by Month from 2000-2010
```{r}
ny_noaa |> 
  filter(year == c(2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010)) |> 
  group_by(year, month) |> 
  summarize(avg_prcp = mean(prcp, na.rm = TRUE)) |> 
  filter(!is.na(avg_prcp)) |> 
  plot_ly(
    x = ~month, y = ~year, z = ~avg_prcp,
    type = "heatmap")
```

