---
title: "4/20 Example"
output: html_document
---

```{r setup, include=FALSE}
options(repos = c(openvolley = "https://openvolley.r-universe.dev",
                  CRAN = "https://cloud.r-project.org"))
#install.packages(c("datavolley", "ovlytics"))
#install.packages("peranavolley")
```

```{r}
library(datavolley)
library(ovlytics)
library(peranavolley)
library(tidyverse)
library(dplyr)
```


```{r}
##dv_example_file = function(choice=1) {
##    assert_that(is.numeric(choice))
##    switch(as.character(choice),
##           "1" = system.file("extdata/example_data.dvw", package = ##"datavolley"),
##           "2" = system.file("extdata/PM06.dvw", package = ##"datavolley"),
##           "3" = system.file("extdata/2022-08-23_NCA-CUB.vsm", package ##= "datavolley"),
##           stop("unrecognized 'choice' value (", choice, ")")
##           )
##}
```

```{r}
sd_lv = dv_read(("./volleydata/data/april20.sdvslv"), insert_technical_timeouts = FALSE)

summary(x)
```

```{r}
dv_fake_coordinates = function(skill, evaluation) {
    assert_that(is.string(skill))
    skill = match.arg(tolower(skill), c("serve"))
    assert_that(is.character(evaluation))
    evaluation = tolower(evaluation)
    N = length(evaluation)
    intsample = function(N, from, to) sample.int(to-from+1, size=N, replace=TRUE)+from-1
    if (skill %eq% "serve") {
        ## default to legal starting and ending locations
        s_x = intsample(N, 11, 90)
        s_y = intsample(N, 1, 8)
        e_x = intsample(N, 11, 90)
        e_y = intsample(N, 55, 91)
        ## serve errors
        temp = runif(N)
        ## make 1/5 of them foot faults (illegal starting location)
        idx = evaluation %eq% "error" & temp>0.8
        s_y[idx] = intsample(sum(idx), 11, 13)
        ## and the remainder an illegal ending location
        idx = evaluation %eq% "error" & temp<=0.1 ## net fault
        e_y[idx] = intsample(sum(idx), 50, 51)
        idx = evaluation %eq% "error" & temp>0.1 & temp<=0.8 ## out of bounds
        e_y[idx] = intsample(sum(idx), 92, 101)
    }
    ## s_x etc are grid bin numbers
    ## calculate the corresponding grid index
    s_i = s_x+(s_y-1)*100
    e_i = e_x+(e_y-1)*100
    ## and convert s_x etc to actual court coordinates for plotting
    temp = dv_index2xy(s_i)
    s_x = temp[, 1]
    s_y = temp[, 2]
    temp = dv_index2xy(e_i)
    e_x = temp[, 1]
    e_y = temp[, 2]
    data.frame(start_coordinate=s_i, start_coordinate_x=s_x, start_coordinate_y=s_y,
               end_coordinate=e_i, end_coordinate_x=e_x, end_coordinate_y=e_y)
}
```

```{r}
xserves = subset(plays(sd_lv), skill=="Serve")

xserves$evaluation[!xserves$evaluation %in% c("Ace", "Error")] = "Other"

ggplot(xserves, aes(start_coordinate_x, start_coordinate_y,
        xend=end_coordinate_x, yend=end_coordinate_y, colour=evaluation))+
     geom_segment() + geom_point() +
     scale_colour_manual(values=c(Ace="limegreen", Error="firebrick", Other="dodgerblue")) +
     ggcourt(labels=c("Serving team", "Receiving team"))
```

```{r}
xattacks = subset(plays(sd_lv), skill=="Attack")

xattacks$evaluation[!xattacks$evaluation %in% c("Point", "Error", "Blocked")] = "Other"

ggplot(xattacks, aes(start_coordinate_x, start_coordinate_y,
        xend=end_coordinate_x, yend=end_coordinate_y, colour=evaluation))+
     geom_segment() + geom_point() +
     scale_colour_manual(values=c(Point="limegreen", Error="firebrick", Blocked="pink", Other="dodgerblue")) +
     ggcourt(labels=c("Serving team", "Receiving team"))
```

